  
name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: [ubuntu-latest]
    env:
      name: my-artifact-name
    steps:
    - uses: actions/checkout@v2
        
    - name: 'Upload artifact using v2 preview'	
      uses: actions/upload-artifact@v2-preview
      with:	
        name: 'Repo'
        path: .
